org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=26.3-SNAPSHOT
project.platforms=Common, Fabric, NeoForge
project.plugins=1.1-SNAPSHOT

mod.authors=Fuzs
mod.description=Data maps for everyone: NeoForge's data-driven registry values on Fabric.
mod.group=fuzs.multiloaderdataextensions
mod.id=multiloaderdataextensions
mod.license=MPL-2.0
mod.name=Multiloader Data Extensions
mod.version=26.3.1

dependencies.fabric.fabricapi=required

distributions.github.slug=multiloader-data-extensions

environments.client=required
environments.server=required
