package neoforgesync

import java.io.File
import java.security.MessageDigest
import java.util.zip.ZipFile

enum class SyncMode { GENERATED, OWNED, LOCAL }

data class ManifestEntry(val mode: SyncMode, val path: String)

object NeoForgeSourcesSync {
    const val UPSTREAM_PREFIX = "net.neoforged.neoforge."
    private const val UPSTREAM_ROOT = "net/neoforged/neoforge/"

    fun parseManifest(file: File): List<ManifestEntry> {
        return file.readLines()
            .map { it.substringBefore('#').trim() }
            .filter { it.isNotEmpty() }
            .map { line ->
                val parts = line.split(Regex("\\s+"), limit = 2)
                require(parts.size == 2) { "Invalid manifest line: '$line'" }
                val mode = when (parts[0].lowercase()) {
                    "generated" -> SyncMode.GENERATED
                    "owned" -> SyncMode.OWNED
                    "local" -> SyncMode.LOCAL
                    else -> error("Unknown sync mode '${parts[0]}' in: '$line'")
                }
                ManifestEntry(mode, parts[1].trim())
            }
    }

    fun extractSources(sourcesJar: File, targetDir: File) {
        require(sourcesJar.isFile) { "NeoForge sources jar not found: $sourcesJar" }
        targetDir.mkdirs()
        ZipFile(sourcesJar).use { zip ->
            val entries = zip.entries()
            while (entries.hasMoreElements()) {
                val entry = entries.nextElement()
                if (entry.isDirectory || !entry.name.startsWith(UPSTREAM_ROOT)) continue
                val out = File(targetDir, entry.name.removePrefix(UPSTREAM_ROOT))
                out.parentFile.mkdirs()
                zip.getInputStream(entry).use { input -> out.outputStream().use { input.copyTo(it) } }
            }
        }
    }

    fun relocate(text: String, packagePrefix: String): String =
        text.replace(UPSTREAM_PREFIX, "$packagePrefix.")

    fun sha256(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")
        file.inputStream().use { input ->
            val buffer = ByteArray(8192)
            while (true) {
                val read = input.read(buffer)
                if (read < 0) break
                digest.update(buffer, 0, read)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }
}

object NeoForgeLock {
    private const val VERSION_KEY = "neoforge.version"

    fun read(file: File): Map<String, String> {
        if (!file.isFile) return emptyMap()
        return file.readLines()
            .map { it.substringBefore('#').trim() }
            .filter { it.contains('=') }
            .associate { val index = it.indexOf('='); it.substring(0, index).trim() to it.substring(index + 1).trim() }
    }

    fun version(entries: Map<String, String>): String? = entries[VERSION_KEY]

    fun ownedHashes(entries: Map<String, String>): Map<String, String> =
        entries.filterKeys { it != VERSION_KEY }

    fun write(file: File, version: String, ownedHashes: Map<String, String>) {
        file.parentFile.mkdirs()
        file.writeText(buildString {
            appendLine("# Generated by :Fabric:syncNeoForgeSources. Do not edit.")
            appendLine("# Upstream hashes of 'owned' files are used by :Fabric:checkNeoForgeSources to detect drift.")
            appendLine("$VERSION_KEY=$version")
            ownedHashes.toSortedMap().forEach { (path, hash) -> appendLine("$path=$hash") }
        })
    }
}

data class ExecOutcome(val exitValue: Int, val output: String)

class NeoForgeSourcesGenerator(private val exec: (File, List<String>) -> ExecOutcome) {
    data class FileOutcome(val path: String, val mode: SyncMode, val patched: Boolean, val patchOutput: String = "")
    data class Result(val outcomes: List<FileOutcome>, val ownedHashes: Map<String, String>)

    fun generate(
        manifestFile: File,
        patchesDir: File,
        outputDir: File,
        workDir: File,
        sourcesJar: File,
        packagePrefix: String,
        reportDir: File?,
    ): Result {
        val upstreamDir = File(workDir, "upstream")
        val stagingDir = File(workDir, "staging")
        upstreamDir.deleteRecursively()
        stagingDir.deleteRecursively()
        NeoForgeSourcesSync.extractSources(sourcesJar, upstreamDir)

        val ownedHashes = sortedMapOf<String, String>()
        val outcomes = mutableListOf<FileOutcome>()
        for (entry in NeoForgeSourcesSync.parseManifest(manifestFile)) {
            val upstream = File(upstreamDir, entry.path)
            when (entry.mode) {
                SyncMode.LOCAL -> outcomes += FileOutcome(entry.path, entry.mode, patched = false)

                SyncMode.OWNED -> {
                    require(upstream.isFile) { "Missing upstream file for owned entry: ${entry.path}" }
                    ownedHashes[entry.path] = NeoForgeSourcesSync.sha256(upstream)
                    reportDir?.let { dir ->
                        val dest = File(dir, entry.path)
                        dest.parentFile.mkdirs()
                        upstream.copyTo(dest, overwrite = true)
                    }
                    outcomes += FileOutcome(entry.path, entry.mode, patched = false)
                }

                SyncMode.GENERATED -> {
                    require(upstream.isFile) { "Missing upstream file for generated entry: ${entry.path}" }
                    val staged = File(stagingDir, entry.path)
                    staged.parentFile.mkdirs()
                    upstream.copyTo(staged, overwrite = true)

                    val patch = File(patchesDir, "${entry.path}.patch")
                    var patched = false
                    var patchOutput = ""
                    if (patch.isFile) {
                        patched = true
                        val outcome = exec(stagingDir, listOf("patch", "-p1", "-i", patch.absolutePath))
                        patchOutput = outcome.output
                        check(outcome.exitValue == 0) {
                            "Failed to apply patch '${patch.name}' (patch exit code ${outcome.exitValue}).\n" +
                                patchOutput.trim() + "\n" +
                                "Resolve the conflict and update the patch."
                        }
                    }

                    val relocated = NeoForgeSourcesSync.relocate(staged.readText(), packagePrefix)
                    check(!relocated.contains(NeoForgeSourcesSync.UPSTREAM_PREFIX)) {
                        "Generated file '${entry.path}' still references '${NeoForgeSourcesSync.UPSTREAM_PREFIX}'. " +
                            "The patch must remove or replace every loader-only NeoForge reference."
                    }

                    val out = File(outputDir, entry.path)
                    out.parentFile.mkdirs()
                    out.writeText(relocated)
                    outcomes += FileOutcome(entry.path, entry.mode, patched, patchOutput)
                }
            }
        }
        return Result(outcomes, ownedHashes)
    }
}
