package fuzs.multiloader.vendoredsources

import java.io.File
import java.security.MessageDigest
import java.util.zip.ZipFile

enum class SyncMode { GENERATED, OWNED, LOCAL }

data class ManifestEntry(val mode: SyncMode, val source: String?, val path: String)

/**
 * A single upstream source that vendored files are copied from.
 *
 * @param name        unique name used by manifest entries to reference this source
 * @param version     upstream version, recorded in the lock file
 * @param packageRoot dot-form package root of the source (e.g. `net.neoforged.neoforge`)
 * @param relocateTo  dot-form package the source is relocated to, or `null` to keep the original package
 * @param sourcesJar  the upstream sources jar to copy files from
 */
data class SourceSpec(
    val name: String,
    val version: String,
    val packageRoot: String,
    val relocateTo: String?,
    val sourcesJar: File,
) {
    val packageRootPath: String = packageRoot.replace('.', '/')

    /**
     * {@return the path a source file is written to, relative to the output source directory}
     */
    fun outputPath(sourcePath: String): String {
        val subPath = sourcePath.removePrefix("$packageRootPath/")
        return if (relocateTo != null) "${relocateTo.replace('.', '/')}/$subPath" else sourcePath
    }
}

object VendoredSources {
    fun parseManifest(file: File): List<ManifestEntry> {
        return file.readLines()
            .map { it.substringBefore('#').trim() }
            .filter { it.isNotEmpty() }
            .map { line ->
                val parts = line.split(Regex("\\s+"))
                when (parts[0].lowercase()) {
                    "generated" -> {
                        require(parts.size == 3) { "Invalid manifest line (expected 'generated <source> <path>'): '$line'" }
                        ManifestEntry(SyncMode.GENERATED, parts[1], parts[2])
                    }

                    "owned" -> {
                        require(parts.size == 3) { "Invalid manifest line (expected 'owned <source> <path>'): '$line'" }
                        ManifestEntry(SyncMode.OWNED, parts[1], parts[2])
                    }

                    "local" -> {
                        require(parts.size == 2) { "Invalid manifest line (expected 'local <path>'): '$line'" }
                        ManifestEntry(SyncMode.LOCAL, null, parts[1])
                    }

                    else -> error("Unknown sync mode '${parts[0]}' in: '$line'")
                }
            }
    }

    fun extractSource(sourcesJar: File, packageRootPath: String, targetDir: File) {
        require(sourcesJar.isFile) { "Vendored sources jar not found: $sourcesJar" }
        val prefix = "$packageRootPath/"
        targetDir.mkdirs()
        ZipFile(sourcesJar).use { zip ->
            val entries = zip.entries()
            while (entries.hasMoreElements()) {
                val entry = entries.nextElement()
                if (entry.isDirectory || !entry.name.startsWith(prefix)) continue
                val out = File(targetDir, entry.name)
                out.parentFile.mkdirs()
                zip.getInputStream(entry).use { input -> out.outputStream().use { input.copyTo(it) } }
            }
        }
    }

    fun relocate(text: String, source: SourceSpec): String {
        val target = source.relocateTo ?: return text
        return text.replace("${source.packageRoot}.", "$target.")
    }

    fun sha256(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")
        file.inputStream().use { input ->
            val buffer = ByteArray(8192)
            while (true) {
                val read = input.read(buffer)
                if (read < 0) break
                digest.update(buffer, 0, read)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }
}

object VendoredSourcesLock {
    private const val VERSION_PREFIX = "version."

    fun read(file: File): Map<String, String> {
        if (!file.isFile) return emptyMap()
        return file.readLines()
            .map { it.substringBefore('#').trim() }
            .filter { it.contains('=') }
            .associate { val index = it.indexOf('='); it.substring(0, index).trim() to it.substring(index + 1).trim() }
    }

    fun versions(entries: Map<String, String>): Map<String, String> =
        entries.filterKeys { it.startsWith(VERSION_PREFIX) }.mapKeys { it.key.removePrefix(VERSION_PREFIX) }

    fun ownedHashes(entries: Map<String, String>): Map<String, String> =
        entries.filterKeys { !it.startsWith(VERSION_PREFIX) }

    fun write(file: File, versions: Map<String, String>, ownedHashes: Map<String, String>) {
        file.parentFile.mkdirs()
        file.writeText(buildString {
            appendLine("# Generated by the vendored-sources sync tasks. Do not edit.")
            appendLine("# 'version.*' pins each source; all other entries are upstream hashes of 'owned' files.")
            versions.toSortedMap().forEach { (source, version) -> appendLine("$VERSION_PREFIX$source=$version") }
            ownedHashes.toSortedMap().forEach { (path, hash) -> appendLine("$path=$hash") }
        })
    }
}

data class ExecOutcome(val exitValue: Int, val output: String)

class VendoredSourcesGenerator(private val exec: (File, List<String>) -> ExecOutcome) {
    data class FileOutcome(
        val path: String,
        val source: String?,
        val mode: SyncMode,
        val patched: Boolean,
        val patchOutput: String = "",
    )

    data class Result(val outcomes: List<FileOutcome>, val ownedHashes: Map<String, String>)

    fun generate(
        manifestFile: File,
        patchesDir: File,
        outputDir: File,
        workDir: File,
        sources: List<SourceSpec>,
        reportDir: File?,
    ): Result {
        val sourcesByName = sources.associateBy { it.name }
        val upstreamDirs = sources.associate { source ->
            val dir = File(workDir, "upstream/${source.name}")
            dir.deleteRecursively()
            VendoredSources.extractSource(source.sourcesJar, source.packageRootPath, dir)
            source.name to dir
        }
        val stagingDir = File(workDir, "staging")
        stagingDir.deleteRecursively()

        val ownedHashes = sortedMapOf<String, String>()
        val outcomes = mutableListOf<FileOutcome>()
        for (entry in VendoredSources.parseManifest(manifestFile)) {
            when (entry.mode) {
                SyncMode.LOCAL -> outcomes += FileOutcome(entry.path, null, entry.mode, patched = false)

                SyncMode.OWNED -> {
                    val source = source(sourcesByName, entry)
                    val upstream = File(upstreamDirs.getValue(source.name), entry.path)
                    require(upstream.isFile) {
                        "Missing upstream file for owned entry '${entry.path}' in source '${source.name}'"
                    }
                    ownedHashes[entry.path] = VendoredSources.sha256(upstream)
                    reportDir?.let { dir ->
                        val dest = File(dir, entry.path)
                        dest.parentFile.mkdirs()
                        upstream.copyTo(dest, overwrite = true)
                    }
                    outcomes += FileOutcome(entry.path, source.name, entry.mode, patched = false)
                }

                SyncMode.GENERATED -> {
                    val source = source(sourcesByName, entry)
                    val upstream = File(upstreamDirs.getValue(source.name), entry.path)
                    require(upstream.isFile) {
                        "Missing upstream file for generated entry '${entry.path}' in source '${source.name}'"
                    }
                    val staged = File(stagingDir, entry.path)
                    staged.parentFile.mkdirs()
                    upstream.copyTo(staged, overwrite = true)

                    val patch = File(patchesDir, "${entry.path}.patch")
                    var patched = false
                    var patchOutput = ""
                    if (patch.isFile) {
                        patched = true
                        val outcome = exec(stagingDir, listOf("patch", "-p1", "-i", patch.absolutePath))
                        patchOutput = outcome.output
                        check(outcome.exitValue == 0) {
                            "Failed to apply patch '${patch.name}' (patch exit code ${outcome.exitValue}).\n" +
                                patchOutput.trim() + "\n" +
                                "Resolve the conflict and update the patch."
                        }
                    }

                    val relocated = VendoredSources.relocate(staged.readText(), source)
                    if (source.relocateTo != null) {
                        check(!relocated.contains("${source.packageRoot}.")) {
                            "Generated file '${entry.path}' still references '${source.packageRoot}.'. " +
                                "The patch must remove or replace every loader-only reference."
                        }
                    }

                    val out = File(outputDir, source.outputPath(entry.path))
                    out.parentFile.mkdirs()
                    out.writeText(relocated)
                    outcomes += FileOutcome(entry.path, source.name, entry.mode, patched, patchOutput)
                }
            }
        }
        return Result(outcomes, ownedHashes)
    }

    private fun source(sourcesByName: Map<String, SourceSpec>, entry: ManifestEntry): SourceSpec {
        return sourcesByName[entry.source]
            ?: error("Unknown source '${entry.source}' for manifest entry '${entry.path}'")
    }
}
